-- 코드를 입력하세요
WITH UNION_TABLE as (
SELECT A.ONLINE_SALE_ID "SALE_ID"
     , A.SALES_DATE
     , A.PRODUCT_ID
     , A.USER_ID
     , A.SALES_AMOUNT
  FROM ONLINE_SALE A
UNION ALL
SELECT B.OFFLINE_SALE_ID "SALE_ID"
     , B.SALES_DATE
     , B.PRODUCT_ID
     , NULL "USER_ID"
     , B.SALES_AMOUNT 
  FROM OFFLINE_SALE B
)

select DATE_FORMAT(U.SALES_DATE, '%Y-%m-%d') "SALES_DATE"
     , U.PRODUCT_ID
     , U.USER_ID
     , U.SALES_AMOUNT
  from UNION_TABLE U
 where U.SALES_DATE like '2022-03%'
 order by U.SALES_DATE asc, U.PRODUCT_ID asc, U.USER_ID asc