-- 코드를 입력하세요
SELECT B.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
     , SUM(S.TOTAL_SALES * B.PRICE)"TOTAL_SALES"
FROM  BOOK B
JOIN  (SELECT BOOK_ID
           , SUM(SALES) "TOTAL_SALES"
        FROM BOOK_SALES
       WHERE SALES_DATE LIKE '2022-01%'
       GROUP BY BOOK_ID
      ) S ON(B.BOOK_ID = S.BOOK_ID)
 JOIN AUTHOR A ON(B.AUTHOR_ID = A.AUTHOR_ID)
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC