-- 코드를 작성해주세요
WITH MAX_BY_YEAR AS(
    SELECT YEAR(DIFFERENTIATION_DATE) as "YEAR"
         , MAX(SIZE_OF_COLONY) as "MAX_SIZE"
      FROM ECOLI_DATA
     GROUP BY YEAR
)

SELECT YEAR(ed.DIFFERENTIATION_DATE) as "YEAR"
     , mby.MAX_SIZE - ed.SIZE_OF_COLONY as "YEAR_DEV"
     , ed.ID
  FROM ECOLI_DATA ed
  JOIN MAX_BY_YEAR mby on(YEAR(ed.DIFFERENTIATION_DATE) = mby.YEAR)
 ORDER BY YEAR ASC, YEAR_DEV ASC
  